version: 1.0.{build}
branches:
  only:
  - master
 
before_build:
- ps: nuget restore WebDev.Project\WebDev.Project.sln 
 
build:
  project: WebDev.Project\WebDev.Project.sln
  verbosity: minimal  

after_test: 
  - WebDev.Project\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"WebDev.Project\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"/domain:single  WebDev.Project\WebDev.Data.Tests\bin\Debug\WebDev.Data.Tests.dll WebDev.Project\WebDev.Services.Tests\bin\Debug\WebDev.Services.Tests.dll" -output:coverage.xml

  - WebDev.Project\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
